// app/api/sites/[id]/fix-pack/route.ts
// Returns a structured Fix Pack: a JSON array of ready-to-deploy files
// derived from completed aiRepairActions for a job. The client downloads
// each file individually via Blob URLs — no server-side ZIP dependency needed.
//
// POST /api/sites/[id]/fix-pack
//   body: { jobId: string }
//   returns: { files: FixPackFile[] }

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@clerk/nextjs/server";
import { and, eq } from "drizzle-orm";
import { getDrizzle } from "@/lib/db/postgres";
import { sites } from "@/lib/db/schema/sites/sites";
import { users } from "@/lib/db/schema/auth/users";
import { aiAnalysisJobs, aiRepairActions } from "@/lib/db/schema/ai/analysis";
import type { AiRepairAction } from "@/lib/db/schema/ai/analysis";
import { categoriseSnippet, normaliseHeadSnippet } from "@/lib/optimization/fixes/snippetUtils";

export interface FixPackFile {
  name: string;
  content: string;
  mimeType: string;
  description: string;
}

function categorise(action: AiRepairAction): "head" | "robots" | "htaccess" | "llms" | null {
  const fix = (action.automatedFix ?? {}) as Record<string, unknown>;
  const snippet = ((fix.elaboratedSnippet ?? fix.snippet) as string | null | undefined) ?? "";
  return categoriseSnippet(snippet, action.seoSection);
}

function buildHeadFile(actions: AiRepairAction[], siteUrl: string, date: string): string {
  const lines = [
    `<!-- GetSafe360 SEO Fix Pack — ${siteUrl} — ${date} -->`,
    `<!-- Paste these snippets inside your <head> element -->`,
    ``,
  ];

  for (const a of actions) {
    const fix = (a.automatedFix ?? {}) as Record<string, unknown>;
    const raw = ((fix.elaboratedSnippet ?? fix.snippet) as string) ?? "";
    const snippet = normaliseHeadSnippet(raw) ?? raw.trim();
    const summary = (fix.elaboratedSummary ?? fix.description ?? "") as string;
    lines.push(`<!-- ${a.title} (${a.severity ?? "medium"}) -->`);
    if (summary) lines.push(`<!-- ${summary} -->`);
    lines.push(snippet.trim(), ``);
  }

  return lines.join("\n");
}

function buildRobotsFile(actions: AiRepairAction[], date: string): string {
  const lines = [
    `# GetSafe360 AI-Bot Directives — ${date}`,
    `# Add these lines to your existing robots.txt`,
    ``,
  ];

  for (const a of actions) {
    const fix = (a.automatedFix ?? {}) as Record<string, unknown>;
    const snippet = ((fix.elaboratedSnippet ?? fix.snippet) as string) ?? "";
    lines.push(`# ${a.title ?? ""}`, snippet.trim(), ``);
  }

  return lines.join("\n");
}

function buildHtaccessFile(actions: AiRepairAction[], date: string): string {
  const lines = [
    `# GetSafe360 Security & Server Config — ${date}`,
    `# Add these directives to your .htaccess file`,
    ``,
  ];

  for (const a of actions) {
    const fix = (a.automatedFix ?? {}) as Record<string, unknown>;
    const snippet = ((fix.elaboratedSnippet ?? fix.snippet) as string) ?? "";
    lines.push(`# ${a.title ?? ""}`, snippet.trim(), ``);
  }

  return lines.join("\n");
}

function buildLlmsFile(actions: AiRepairAction[], siteUrl: string, date: string): string {
  const lines = [
    `# GetSafe360 llms.txt — ${siteUrl}`,
    `# Generated: ${date}`,
    ``,
  ];

  for (const a of actions) {
    const fix = (a.automatedFix ?? {}) as Record<string, unknown>;
    const snippet = ((fix.elaboratedSnippet ?? fix.snippet) as string) ?? "";
    if (snippet.trim()) lines.push(snippet.trim(), ``);
  }

  return lines.join("\n");
}

function buildInstructionsFile(actions: AiRepairAction[], siteUrl: string, date: string): string {
  const lines = [
    `# Manual Fix Instructions — ${siteUrl} — ${date}`,
    `# Generated by GetSafe360 AI`,
    ``,
  ];

  for (const a of actions) {
    const fix = (a.automatedFix ?? {}) as Record<string, unknown>;
    const desc = (fix.elaboratedSummary ?? fix.description ?? "") as string;
    const steps = (fix.elaboratedSteps ?? []) as string[];
    lines.push(`## ${a.title ?? a.actionId} (${a.severity ?? "medium"})`);
    if (a.impact) lines.push(a.impact);
    if (desc) lines.push(``, `**What to do:** ${desc}`);
    if (steps.length > 0) {
      lines.push(``);
      steps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
    }
    lines.push(``);
  }

  return lines.join("\n");
}

export async function POST(
  request: NextRequest,
  props: { params: Promise<{ id: string }> },
) {
  const { id: siteId } = await props.params;
  const { userId } = await auth();

  if (!userId) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 });

  const body = await request.json().catch(() => ({})) as { jobId?: string };
  if (!body.jobId) return NextResponse.json({ error: "jobId required" }, { status: 400 });

  const db = getDrizzle();

  const [dbUser] = await db
    .select({ id: users.id })
    .from(users)
    .where(eq(users.clerkUserId, userId))
    .limit(1);

  if (!dbUser) return NextResponse.json({ error: "UNAUTHORIZED" }, { status: 401 });

  const [site] = await db
    .select({ id: sites.id, siteUrl: sites.siteUrl, canonicalHost: sites.canonicalHost })
    .from(sites)
    .where(and(eq(sites.id, siteId), eq(sites.userId, dbUser.id)))
    .limit(1);

  if (!site) return NextResponse.json({ error: "SITE_NOT_FOUND" }, { status: 404 });

  const [job] = await db
    .select({ id: aiAnalysisJobs.id })
    .from(aiAnalysisJobs)
    .where(and(eq(aiAnalysisJobs.id, body.jobId), eq(aiAnalysisJobs.siteId, siteId)))
    .limit(1);

  if (!job) return NextResponse.json({ error: "JOB_NOT_FOUND" }, { status: 404 });

  const actions = await db
    .select()
    .from(aiRepairActions)
    .where(
      and(
        eq(aiRepairActions.analysisJobId, body.jobId),
        eq(aiRepairActions.siteId, siteId),
        eq(aiRepairActions.status, "completed"),
      ),
    );

  const date = new Date().toISOString().split("T")[0]!;
  const siteUrl = site.siteUrl;

  // Bucket actions by target file
  const headActions: AiRepairAction[] = [];
  const robotsActions: AiRepairAction[] = [];
  const htaccessActions: AiRepairAction[] = [];
  const llmsActions: AiRepairAction[] = [];
  const manualActions: AiRepairAction[] = [];

  for (const a of actions) {
    const cat = categorise(a);
    if (cat === "head") headActions.push(a);
    else if (cat === "robots") robotsActions.push(a);
    else if (cat === "htaccess") htaccessActions.push(a);
    else if (cat === "llms") llmsActions.push(a);
    else manualActions.push(a);
  }

  const files: FixPackFile[] = [];

  if (headActions.length > 0) {
    files.push({
      name: "seo-head-snippets.html",
      content: buildHeadFile(headActions, siteUrl, date),
      mimeType: "text/html",
      description: `${headActions.length} JSON-LD and HTML <head> snippet${headActions.length === 1 ? "" : "s"} — paste inside <head>`,
    });
  }

  if (robotsActions.length > 0) {
    files.push({
      name: "robots-additions.txt",
      content: buildRobotsFile(robotsActions, date),
      mimeType: "text/plain",
      description: `AI-bot directives — append to your robots.txt`,
    });
  }

  if (htaccessActions.length > 0) {
    files.push({
      name: "htaccess-additions.txt",
      content: buildHtaccessFile(htaccessActions, date),
      mimeType: "text/plain",
      description: `Apache config directives — append to your .htaccess`,
    });
  }

  if (llmsActions.length > 0) {
    files.push({
      name: "llms.txt",
      content: buildLlmsFile(llmsActions, siteUrl, date),
      mimeType: "text/plain",
      description: `LLM crawler permissions file — deploy to your site root as /llms.txt`,
    });
  }

  if (manualActions.length > 0) {
    files.push({
      name: "manual-instructions.md",
      content: buildInstructionsFile(manualActions, siteUrl, date),
      mimeType: "text/markdown",
      description: `${manualActions.length} manual fix instruction${manualActions.length === 1 ? "" : "s"}`,
    });
  }

  return NextResponse.json({ files, totalActions: actions.length });
}
